### ISSUE TITLE
CLIからサーバー立ち上げ検討

### ISSUE THREAD

**Issue by ampcpmgp** [ampcpmgp/am-coffee-time#3]
以下のようなコマンドから、パターン表示用のサーバーを立ち上げ、モックを表示できるようにしたい
`am-coffee-time --pattern mock/pattern.yml --app mock/app.html`

**Comment by ampcpmgp** [comment]
ツリー用objectとaction設定jsを従来通り分ける。  
分けるが構文を変更。


以下、`readme.md` に書く内容

# config pattern list
am-coffee-timeでは、yamlとjsonを標準で解析します。  
yamlの場合は、拡張子を `yml, yaml` にしてください。

以下が設定例です。
```yaml
url: './accout'
Plan A:
  func: [setPlan, plan/a.json]
  view statistics: 
Plan B:
  func: [setPlan, plan/b.json]
plan C:
  funcs:
   - [setPlan, plan/c.json] 
   - [assert, 403] 
```

## reserved property
### url
設定されたobject配下に対して、リンク先のURLを設定します。  
default値は、 `/` になります。  
他ドメインの設定も可能です。

### func
関数名・引数を入れられます。後述する共通action定義を呼び出します。


### funcs
func を順に定義できます。

## other property
pattern list表示用に利用されます。  
後述するaction定義のkeyになります。
